"""初期スキーマ：users / vehicles / vehicle_events

Revision ID: 2ea54fef64b3
Revises: 
Create Date: 2026-08-24 12:59:33.146936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea54fef64b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('staff', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_no', sa.Text(), nullable=False),
    sa.Column('maker', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('displacement', sa.Text(), nullable=True),
    sa.Column('price_yen', sa.Integer(), nullable=False),
    sa.Column('shaken_expires_on', sa.Text(), nullable=True),
    sa.Column('repair_history', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='IN_STOCK', nullable=False),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.Text(), nullable=True),
    sa.Column('lock_expires_at', sa.Text(), nullable=True),
    sa.Column('lock_note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('IN_STOCK', 'NEGOTIATING', 'SOLD')", name='ck_vehicles_status'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_no')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicles_status', ['status'], unique=False)

    op.create_table('vehicle_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_intent', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_events', schema=None) as batch_op:
        batch_op.create_index('idx_events_vehicle', ['vehicle_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_vehicle')

    op.drop_table('vehicle_events')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('idx_vehicles_status')

    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
